language: ruby
rvm:
  - 2.0.0

addons:
  code_climate:
    repo_token:

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000
    - SECURITY_SECRET_TOKEN=traviscitraviscitraviscitraviscitravisci

services:
  - postgresql

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c "CREATE USER rails-bootstrap WITH PASSWORD 'rails-bootstrap';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS rails-bootstrap_test;" -U postgres
  - psql -c "CREATE DATABASE rails-bootstrap_test ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate test:prepare

script:
  - bundle exec rspec
  - bundle exec rubocop app spec -R --format simple

